sudo: required

language: java

jdk: openjdk8

services:
  - docker

env:
  - NXF_VER=0.23.0

install:
  - curl -fsSL get.nextflow.io | bash
  - chmod 755 nextflow
  - sudo ln -s ~/nextflow /usr/local/bin/

script:
  - ./test/test_docker.sh
