sudo: required

language: java

jdk: openjdk8

services:
  - docker

env:
  - NXF_VER=0.25.6 SGT_VER=2.3.1 PROFILE=singularityTest TEST=ANNOTATE
  - NXF_VER=0.25.6 SGT_VER=2.3.1 PROFILE=travis TEST=ANNOTATE
  - NXF_VER=0.25.6 SGT_VER=2.3.1 PROFILE=singularityTest TEST=RECALIBRATE
  - NXF_VER=0.25.6 SGT_VER=2.3.1 PROFILE=travis TEST=RECALIBRATE
  - NXF_VER=0.25.6 SGT_VER=2.3.1 PROFILE=singularityTest TEST=REALIGN
  - NXF_VER=0.25.6 SGT_VER=2.3.1 PROFILE=travis TEST=REALIGN
  - NXF_VER=0.25.6 SGT_VER=2.3.1 PROFILE=singularityTest TEST=MAPPING
  - NXF_VER=0.25.6 SGT_VER=2.3.1 PROFILE=travis TEST=MAPPING

install: # Install Nextflow
  - "./scripts/install.sh --tool nextflow"

script:
  - "./scripts/test.sh --profile $PROFILE --test $TEST --install --travisci"
